/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface MyPluginNrThree {
      'first': string;
      'last': string;
    }
  }

  interface HTMLMyPluginNrThreeElement extends StencilComponents.MyPluginNrThree, HTMLStencilElement {}

  var HTMLMyPluginNrThreeElement: {
    prototype: HTMLMyPluginNrThreeElement;
    new (): HTMLMyPluginNrThreeElement;
  };
  interface HTMLElementTagNameMap {
    'my-plugin-nr-three': HTMLMyPluginNrThreeElement;
  }
  interface ElementTagNameMap {
    'my-plugin-nr-three': HTMLMyPluginNrThreeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-plugin-nr-three': JSXElements.MyPluginNrThreeAttributes;
    }
  }
  namespace JSXElements {
    export interface MyPluginNrThreeAttributes extends HTMLAttributes {
      'first'?: string;
      'last'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;